---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: default
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
---
apiVersion: v1
kind: Service
metadata:
  name: multilevel-db-test
  labels:
    app: multilevel-db-test
spec:
  ports:
  - port: 9000
  clusterIP: None
  selector:
    app: multilevel-db-test
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: multilevel-db-test
spec:
  serviceName: "multilevel-db-test"
  replicas: 1
  template:
    metadata:
      labels:
        app: multilevel-db-test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: multilevel-db-test
        image: interlincx/multilevel-db:v2.0.0
        ports:
        - containerPort: 9000
          name: db
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: PORT
          value: 9000
        - name: DB
          value: '/data'
        - name: DB_NAME
          value: 'app-name'
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
          requests:
              storage: 10Gi
